server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: office-routes
    consumer:
      group-id: OfficeGroupId
      auto-offset-reset: latest

application:
  airports:
    - name: "North America"
      x: 10
      y: 10
    - name: "Africa"
      x: 50
      y: 65
    - name: "Asia"
      x: 75
      y: 35
    - name: "South America"
      x: 23
      y: 70
    - name: "Australia"
      x: 85
      y: 75
    - name: "Europe"
      x: 50
      y: 22